accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login', LogInView, name='login'),
    path('logout', LogOutView, name='logout'),
    path('activate/<uidb64>/<token>/', VerificationView, name='activate'),
    path('request-reset-email/', RequestResetEmail, name="request-reset-email"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView, name='reset-password'),

    path('register-doctor/', DoctorRegistration, name='register-doctor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', include('customadmin.urls', namespace='custom-admin')),
    path('notification/', include('notification.urls', namespace='notification')),
]

# static and media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="Kenyatta Hospital Child Immunization Tracking System"
admin.site.site_title="Kenyatta Hospital Child Immunization Tracking System"

# error pages
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

core/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', IndexView, name='index'),
    path('parent_dashboard/', ParentDashboard, name='parent-dashboard'),
    path('parent-profile-update/', parent_profile_settings, name='parent-profile-update'),
    path('parent-dashboard/change-password/', dashboard_change_password, name='dashboard-change-password'),
    path('child-profile/<uuid>/', child_profile, name='child-profile'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),

    path('child/immunization-detail/<uuid:uuid>/', child_immunization_detail, name='child-immunization-detail'),

    path('doctor-dashboard/', doctor_dashboard, name='doctor-dashboard'),
    path('doctor-children-assigned/', doctor_children_assigned, name='doctor-children-assigned'),
    path('doctor-appointments/', doctor_appintments, name='doctor-appointments'),
    path('doctor-profile-settings/', doctor_profile_update, name='doctor-profile-update'),


    path('create-child/', create_child, name='create-child'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),
    path('child-profile-delete/<uuid:uuid>/', delete_child, name='child-delete'),

    path('clients/', clients, name='clients'),

    path('terms-and-conditions/', terms_and_conditions, name='terms-and-conditions'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
]

customadmin/urls.py
from django.urls import path

from customadmin.views import *

app_name = 'custom-admin'

urlpatterns = [
    path('', IndexView, name='index'),
    path('doctors/', DoctorList, name='doctors'),
    path('doctors/<int:pk>/', DoctorDetail, name='doctor-detail'),
    path('doctors/<int:pk>/suspend/', suspendDoctor, name='suspend-doctor'),
    path('doctors/<int:pk>/delete/', DoctorDelete, name='doctor-delete'),
    path('doctors/create/', DoctorCreate, name='doctor-create'),
    path('parents/', ParentList, name='parents'),
    path('parents/<int:pk>/', ParentDetail, name='parent-detail'),
    path('parents/<int:pk>/delete/', ParentDelete, name='parent-delete'),
    path('parents/create/', ParentCreate, name='parent-create'),
    path('children/', ChildList, name='children'),
    path('children/<int:pk>/', ChildDetail, name='child-detail'),
    path('children/<int:pk>/delete/', ChildDelete, name='child-delete'),
    path('children/create/', ChildCreate, name='child-create'),
    path('vaccines/', VaccinesList, name='vaccines'),
    path('vaccines/<int:pk>/', VaccinesDetail, name='vaccines-detail'),
    path('vaccines/<int:pk>/delete/', VaccinesDelete, name='vaccines-delete'),
    path('vaccines/create/', VaccinesCreate, name='vaccines-create'),
    path('counties/', CountiesList, name='counties'),
    path('counties/<slug>/', CountiesDetail, name='counties-detail'),
    path('hospitals/', HospitalList, name='hospitals'),
    path('hospitals/<uuid>/', HospitalDetail, name='hospital-detail'),
    path('hospitals/<uuid>/delete/', HospitalDelete, name='hospital-delete'),
    

    
]

frontend/templates/admin-dash/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
        <title>VacTrac - {% block title %}{% endblock title %}</title>
		
		<!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">
		
		<!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
        <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/font-awesome.min.css' %}">
		
		<!-- Feathericon CSS -->
        <link rel="stylesheet" href="{% static 'admin-static/assets/css/feathericon.min.css' %}">
		
		<link rel="stylesheet" href="{% static 'admin-static/assets/plugins/morris/morris.css' %}">
		
		<!-- Main CSS -->
        <link rel="stylesheet" href="{% static 'admin-static/assets/css/style.css' %}">
		
		<!--[if lt IE 9]>
			<script src="assets/js/html5shiv.min.js"></script>
			<script src="assets/js/respond.min.js"></script>
		<![endif]-->
    </head>
    <body>
	
		<!-- Main Wrapper -->
        <div class="main-wrapper">
		
			<!-- Header -->
            <div class="header">
			
				<!-- Logo -->
                <div class="header-left">
                    <a href="{% url 'custom-admin:index' %}" class="logo">
						<img src="{% static 'assets/img/logo.png' %}" alt="Logo">
					</a>
					<a href="{% url 'custom-admin:index' %}" class="logo logo-small">
						<img src="{% static 'admin-static/assets/img/logo-small.png' %}" alt="Logo" width="30" height="30">
					</a>
                </div>
				<!-- /Logo -->
				
				<a href="javascript:void(0);" id="toggle_btn">
					<i class="fe fe-text-align-left"></i>
				</a>
				
				<div class="top-nav-search">
					<form>
						<input type="text" class="form-control" placeholder="Search here">
						<button class="btn" type="submit"><i class="fa fa-search"></i></button>
					</form>
				</div>
				
				<!-- Mobile Menu Toggle -->
				<a class="mobile_btn" id="mobile_btn">
					<i class="fa fa-bars"></i>
				</a>
				<!-- /Mobile Menu Toggle -->
				
				<!-- Header Right Menu -->
				<ul class="nav user-menu">

					<!-- Notifications -->
					<li class="nav-item dropdown noti-dropdown">
						<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
							<i class="fe fe-bell"></i> <span class="badge badge-pill">3</span>
						</a>
						
					</li>
					<!-- /Notifications -->
					
					<!-- User Menu -->
					<li class="nav-item dropdown has-arrow">
						<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
							<span class="user-img"><img class="rounded-circle" src="{{ request.user.profile_picture_thumbnail.url }}" width="31" alt="Ryan Taylor"></span>
						</a>
						<div class="dropdown-menu">
							<div class="user-header">
								<div class="avatar avatar-sm">
									<img src="{{ request.user.profile_picture_thumbnail.url }}" alt="User Image" class="avatar-img rounded-circle">
								</div>
								<div class="user-text">
									<h6>{{ request.user.username }}</h6>
									<p class="text-muted mb-0">Administrator</p>
								</div>
							</div>
							<a class="dropdown-item" href="#">My Profile</a>
							<a class="dropdown-item" href="#">Settings</a>
							<a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
						</div>
					</li>
					<!-- /User Menu -->
					
				</ul>
				<!-- /Header Right Menu -->
				
            </div>
			<!-- /Header -->
			
			<!-- Sidebar -->
            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
					<div id="sidebar-menu" class="sidebar-menu">
						<ul>
							<li class="menu-title"> 
								<span>Main</span>
							</li>
							<li class=""> 
								<a href="{% url 'custom-admin:index' %}"><i class="fe fe-home"></i> <span>Dashboard</span></a>
							</li>
							<li class=""> 
								<a href="{% url 'custom-admin:hospitals' %}"><i class="fe fe-plus"></i> <span>Hospitals/Clients</span></a>
							</li>
							<li> 
								<a href="{% url 'custom-admin:vaccines' %}"><i class="fe fe-users"></i> <span>Vaccines</span></a>
							</li>
							<li> 
								<a href="{% url 'custom-admin:doctors' %}"><i class="fe fe-user-plus"></i> <span>Doctors</span></a>
							</li>
							<li> 
								<a href="{% url 'custom-admin:parents' %}"><i class="fe fe-user"></i> <span>Parents</span></a>
							</li>
							<li> 
								<a href="{% url 'custom-admin:children' %}"><i class="fe fe-user"></i> <span>Children Records</span></a>
							</li>
							<li class="menu-title"> 
								<span>Pages</span>
							</li>
							<li class="submenu">
								<a href="#"><i class="fe fe-document"></i> <span> Authentication </span> <span class="menu-arrow"></span></a>
								<ul style="display: none;">
									{% if request.user.is_authenticated %}
										<li><a href="{% url 'accounts:logout' %}"> Logout </a></li>
									{% endif %}
									<li><a href="#"> Register MOH </a></li>
									<li><a href="#"> Forgot Password </a></li>
									<li><a href="#"> Lock Screen </a></li>
								</ul>
							</li>
							
						
							
						</ul>
					</div>
                </div>
            </div>
			<!-- /Sidebar -->

        
            {% block body %}
            
            
            
            {% endblock body %}



        </div>
		<!-- /Main Wrapper -->
		
		<!-- jQuery -->
        <script src="{% static 'admin-static/assets/js/jquery-3.2.1.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
        <script src="{% static 'admin-static/assets/js/popper.min.js' %}"></script>
        <script src="{% static 'admin-static/assets/js/bootstrap.min.js' %}"></script>
		
		<!-- Slimscroll JS -->
        <script src="{% static 'admin-static/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
		
		<script src="{% static 'admin-static/assets/plugins/raphael/raphael.min.js' %}"></script>    
		<script src="{% static 'admin-static/assets/plugins/morris/morris.min.js' %}"></script>  
		<script src="{% static 'admin-static/assets/js/chart.morris.js' %}"></script>
		
		<!-- Custom JS -->
		<script  src="{% static 'admin-static/assets/js/script.js' %}"></script>
		
    </body>
</html>

frontend/templates/admin-dash/children.html
{% extends 'admin-dash/base.html' %}
{% load static %}

{% block title %} Children Records {% endblock title %}

{% block body %}


			
			<!-- Page Wrapper -->
            <div class="page-wrapper">
                <div class="content container-fluid">
				
					<!-- Page Header -->
					<div class="page-header">
						<div class="row">
							<div class="col-sm-12">
								<h3 class="page-title">List of Child Records</h3>
								<ul class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'custom-admin:index' %}">Dashboard</a></li>
									<li class="breadcrumb-item"><a href="javascript:(0);">Users</a></li>
									<li class="breadcrumb-item active">Child Records</li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /Page Header -->
					
					<div class="row">
						<div class="col-sm-12">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<div class="table-responsive">
										<table class="datatable table table-hover table-center mb-0">
											<thead>
												<tr>
													<th>Child's ID</th>
													<th>Child's Name</th>
													<th>Age</th>
													<th>Address</th>
													<th>Parent Phone</th>
												</tr>
											</thead>
											<tbody>
											
                                                {% for child in children %}
                                                
                                                    <tr>
                                                        <td>#{{child.child_id}}</td>
                                                        <td>
                                                            <h2 class="table-avatar">
                                                               
                                                                <a href="{{child.get_absolute_url}}">{{child.first_name}} {{child.last_name}} </a>
                                                            </h2>
                                                        </td>
                                                        <td>{{ child.get_child_age }} month</td>
                                                        <td>{{ child.resident_county }}</td>
                                                        <td>{{ child.parent.user.phone_no }}</td>
                                                    </tr>
                                                
                                                {% endfor %}
												
											</tbody>
										</table>
									</div>
									</div>
								</div>
							</div>
						</div>			
					</div>
					
				</div>			
			</div>
			<!-- /Page Wrapper -->
		

{% endblock body %}

frontend/templates/admin-dash/hospitals.html
{% extends 'admin-dash/base.html' %}
{% load static %}

{% block title %} Parents  {% endblock title %}  

{% block body %}

<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
                <div class="row">
                    <div class="col-sm-7 col-auto">
                        <h3 class="page-title">Hospital</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'custom-admin:hospitals' %}">Dashboard</a></li>
                            <li class="breadcrumb-item active">Hospital</li>
                        </ul>
                    </div>
                    <div class="col-sm-5 col">
                        <a href="#Add_Hospital" data-toggle="modal" class="btn btn-primary float-right mt-2">Add</a>
                    </div>
                </div>
        </div>
        <!-- /Page Header -->
        
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <div class="table-responsive">
                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>Hospital ID</th>
                                        <th>Hospital Name</th>
                                        <th>County</th>
                                        <th>Address</th>
                                        <th>Phone</th>
                                        <th class="text-right">Action</th>
                                    </tr>
                                </thead>
                                <tbody>


                                    {% for hospital in hospitals %}
                                    
                                    <tr>
                                        <td>#{{ hospital.id }}</td>
                                        <td>
                                            <h2 class="table-avatar">
                                                
                                                <a href="{{ hospital.get_absolute_url }}">{{ hospital.name }} </a>
                                            </h2>
                                        </td>
                                        <td>{{ hospital.county.name }}</td>
                                        <td>{{ hospital.address }}</td>
                                        <td>{{hospital.phone_no}}</td>
                                        <td class="text-right">
                                            <div class="actions">
                                                <a class="btn btn-sm bg-success-light" href="">
                                                    <i class="fe fe-pencil"></i> View
                                                </a>
                                                <a  data-toggle="modal" href="#delete_modal_{{ hospital.uuid }}" class="btn btn-sm bg-danger-light">
                                                    <i class="fe fe-trash"></i> Delete
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                </div>
            </div>			
        </div>
        
    </div>			
</div>

<!-- Add Modal -->
<div class="modal fade" id="Add_Hospital" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Hospial</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'custom-admin:hospitals' %}" method="POST">
                    {% csrf_token %}
                    <div class="row form-row">
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Hospital</label>
                                {{ form.name }}
                                <small><span class='text-danger'>{{ form.name.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Licence Number</label>
                                {{ form.license_no }}
                                <small><span class='text-danger'>{{ form.license_no.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>County</label>
                                {{ form.county }}
                                <small><span class='text-danger'>{{ form.county.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Mobile No</label>
                                {{ form.phone_no }}
                                <small><span class='text-danger'>{{ form.phone_no.errors }}</span></small>
                                
                            </div>
                        </div>

                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label>Adress</label>
                                {{ form.address }}
                                <small><span class='text-danger'>{{ form.address.errors }}</span></small>
                            </div>
                        </div>

                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label>Image</label>
                                {{ form.image }}
                                <small><span class='text-danger'>{{ form.image.errors }}</span></small>
                            </div>
                        </div>
                        
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /ADD Modal -->


<!-- Delete Modal -->
{% for hospital in hospitals %}
    <div class="text-center modal fade" id="delete_modal_{{ hospital.uuid }}" aria-hidden="true" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document" >
            <div class="modal-content">
                <div class="modal-body">
                    <div class="form-content p-2">
                        <h4 class="modal-title">Delete</h4>
                        <p class="mb-4">Are you sure want to delete?</p>
                        <a href="{% url 'custom-admin:hospital-delete' hospital.uuid %}"><button type="button" class="btn btn-primary">Confirm </button></a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<!-- /Delete Modal -->

{% endblock body %}

frontend/templates/admin-dash/vaccines.html
{% extends 'admin-dash/base.html' %}
{% load static %}

{% block title %}Vaccines{% endblock title %}

{% block body %}

<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-7 col-auto">
                    <h3 class="page-title">Vaccines</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'custom-admin:index' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Vaccines</li>
                    </ul>
                </div>
                <div class="col-sm-5 col">
                    <a href="#Add_Vaccine_details" data-toggle="modal" class="btn btn-primary float-right mt-2">Add</a>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Vaccine</th>
                                        <th>Time Given</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {% for vaccine in vaccines %}
                                        <tr>
                                            <td>#{{ vaccine.vaccine_id }}</td>
                                            
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="{% url 'custom-admin:vaccines-detail' vaccine.pk %}">{{ vaccine.name }}</a>
                                                </h2>
                                            </td>
                                            <td>
                                                <h2 class="table-avatar">
                                                    <a href="profile.html">{{ vaccine.time_given }}</a>
                                                </h2>
                                            </td>
                                        
                                            <td class="text-right">
                                                <div class="actions">
                                                    <a class="btn btn-sm bg-success-light" href="{% url 'custom-admin:vaccines-detail' vaccine.pk %}">
                                                        <i class="fe fe-pencil"></i> View
                                                    </a>
                                                    <a  data-toggle="modal" href="#delete_modal_{{ vaccine.id }}" class="btn btn-sm bg-danger-light">
                                                        <i class="fe fe-trash"></i> Delete
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>			
        </div>
    </div>			
</div>
<!-- /Page Wrapper -->


<!-- Add Modal -->
<div class="modal fade" id="Add_Vaccine_details" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Vaccine</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'custom-admin:vaccines' %}" method="POST">{% csrf_token %}
                    <div class="row form-row">
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Vaccine</label>
                                {{ form.name }}
                                <small><span class='text-danger'>{{ form.name.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Time Given</label>
                                {{ form.time_given }}
                                <small><span class='text-danger'>{{ form.time_given.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label>Description</label>
                                {{ form.description }}
                                <small><span class='text-danger'>{{ form.description.errors }}</span></small>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6">
                            <div class="form-group">
                                <label>Order</label>
                                {{ form.order }}
                                <small><span class='text-danger'>{{ form.order.errors }}</span></small>
                                
                            </div>
                        </div>
                        
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- /ADD Modal -->

<!-- Delete Modal -->
{% for vaccine in vaccines %}
    <div class="text-center modal fade" id="delete_modal_{{ vaccine.id }}" aria-hidden="true" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document" >
            <div class="modal-content">
                <div class="modal-body">
                    <div class="form-content p-2">
                        <h4 class="modal-title">Delete</h4>
                        <p class="mb-4">Are you sure want to delete?</p>
                        <a href="{% url 'custom-admin:vaccines-delete' vaccine.id %}"><button type="button" class="btn btn-primary">Confirm </button></a>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
<!-- /Delete Modal -->
</div>

{% endblock body %}