accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login', LogInView, name='login'),
    path('logout', LogOutView, name='logout'),
    path('activate/<uidb64>/<token>/', VerificationView, name='activate'),
    path('request-reset-email/', RequestResetEmail, name="request-reset-email"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView, name='reset-password'),

    path('register-doctor/', DoctorRegistration, name='register-doctor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', include('customadmin.urls', namespace='custom-admin')),
    path('notification/', include('notification.urls', namespace='notification')),
]

# static and media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="Kenyatta Hospital Child Immunization Tracking System"
admin.site.site_title="Kenyatta Hospital Child Immunization Tracking System"

# error pages
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

core/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', IndexView, name='index'),
    path('parent_dashboard/', ParentDashboard, name='parent-dashboard'),
    path('parent-profile-update/', parent_profile_settings, name='parent-profile-update'),
    path('parent-dashboard/change-password/', dashboard_change_password, name='dashboard-change-password'),
    path('child-profile/<uuid>/', child_profile, name='child-profile'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),

    path('child/immunization-detail/<uuid:uuid>/', child_immunization_detail, name='child-immunization-detail'),

    path('doctor-dashboard/', doctor_dashboard, name='doctor-dashboard'),
    path('doctor-children-assigned/', doctor_children_assigned, name='doctor-children-assigned'),
    path('doctor-appointments/', doctor_appintments, name='doctor-appointments'),
    path('doctor-profile-settings/', doctor_profile_update, name='doctor-profile-update'),


    path('create-child/', create_child, name='create-child'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),
    path('child-profile-delete/<uuid:uuid>/', delete_child, name='child-delete'),

    path('clients/', clients, name='clients'),

    path('terms-and-conditions/', terms_and_conditions, name='terms-and-conditions'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
]

notification/urls.py
from django.urls import re_path, path

from .views import *

app_name = 'notification'

urlpatterns = [
    path('doctor-send-notification/', doctor_send_notification, name='doctor-send-notification'),
]

frontend/templates/partials/doctor_profile_sidebar.html
{% load static %}

<div class="profile-sidebar">
    <div class="widget-profile pro-widget-content">
        <div class="profile-info-widget">
            <a href="#" class="booking-doc-img">
                <img src="{{ doctor.profile_picture_thumbnail.url }}" alt="User Image">
            </a>
            <div class="profile-det-info">
                <h3>Dr {{ doctor.user.username }}</h3>
                
                <div class="patient-details">
                    <h5 class="mb-0"></h5>
                </div>
            </div>
        </div>
    </div>
    <div class="dashboard-widget">
        <nav class="dashboard-menu">
            <ul>
                <li class="active">
                    <a href="{% url 'core:doctor-dashboard' %}">
                        <i class="fas fa-columns"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:doctor-appointments' %}">
                        <i class="fas fa-calendar-check"></i>
                        <span>Appointments</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:doctor-children-assigned' %}">
                        <i class="fas fa-user-injured"></i>
                        <span>Children Records</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-hourglass-start"></i>
                        <span>Schedule Timings</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-file-invoice"></i>
                        <span>Invoices</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'notification:doctor-send-notification' %}">
                        <i class="fas fa-comments"></i>
                        <span>Send Notifications</span>
                        <small class="unread-msg">23</small>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:doctor-profile-update' %}">
                        <i class="fas fa-user-cog"></i>
                        <span>Profile Settings</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-share-alt"></i>
                        <span>Social Media</span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-lock"></i>
                        <span>Change Password</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                        <span>Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

frontend/templates/partials/messages.html
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
        </div>
    {% endfor %}

{% endif %}
    

frontend/templates/partials/parent-profile-sidebar.html
{% load static %}


<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
    <div class="profile-sidebar">
        <div class="widget-profile pro-widget-content">
            <div class="profile-info-widget">
                <a href="#" class="booking-doc-img">
                    <img src="{{ request.user.parent.profile_picture_thumbnail.url }}" alt="User Image">
                </a>
                <div class="profile-det-info">
                    <h3>{{ parent.user.username }}</h3>
                    <div class="patient-details">
                        <h5><i class="fas fa-birthday-cake"></i> 24 Jul 1983, 38 years</h5>
                        <h5 class="mb-0"><i class="fas fa-map-marker-alt"></i> Newyork, USA</h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="dashboard-widget">
            <nav class="dashboard-menu">
                <ul>
                    <li>
                        <a href="{% url 'core:parent-dashboard' %}">
                            <i class="fas fa-columns"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                  
                    <li class="">
                        <a href="">
                            <i class="fas fa-user-cog"></i>
                            <span>Profile Settings</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'core:dashboard-change-password' %}">
                            <i class="fas fa-lock"></i>
                            <span>Change Password</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

    </div>
</div>