accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('login', LogInView, name='login'),
    path('logout', LogOutView, name='logout'),
    path('activate/<uidb64>/<token>/', VerificationView, name='activate'),
    path('request-reset-email/', RequestResetEmail, name="request-reset-email"),
    path('reset-password/<uidb64>/<token>/', ResetPasswordView, name='reset-password'),

    path('register-doctor/', DoctorRegistration, name='register-doctor'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superadmin/', admin.site.urls),
    
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', include('customadmin.urls', namespace='custom-admin')),
    path('notification/', include('notification.urls', namespace='notification')),
]

# static and media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="Kenyatta Hospital Child Immunization Tracking System"
admin.site.site_title="Kenyatta Hospital Child Immunization Tracking System"

# error pages
handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

core/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'core'


urlpatterns = [
    path('', IndexView, name='index'),
    path('parent_dashboard/', ParentDashboard, name='parent-dashboard'),
    path('parent-profile-update/', parent_profile_settings, name='parent-profile-update'),
    path('parent-dashboard/change-password/', dashboard_change_password, name='dashboard-change-password'),
    path('child-profile/<uuid>/', child_profile, name='child-profile'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),

    path('child/immunization-detail/<uuid:uuid>/', child_immunization_detail, name='child-immunization-detail'),

    path('doctor-dashboard/', doctor_dashboard, name='doctor-dashboard'),
    path('doctor-children-assigned/', doctor_children_assigned, name='doctor-children-assigned'),
    path('doctor-appointments/', doctor_appintments, name='doctor-appointments'),
    path('doctor-profile-settings/', doctor_profile_update, name='doctor-profile-update'),


    path('create-child/', create_child, name='create-child'),
    path('child-profile-update/<uuid>/', child_profile_update, name='child-profile-update'),
    path('child-profile-delete/<uuid:uuid>/', delete_child, name='child-delete'),

    path('clients/', clients, name='clients'),

    path('terms-and-conditions/', terms_and_conditions, name='terms-and-conditions'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
]

notification/urls.py
from django.urls import re_path, path

from .views import *

app_name = 'notification'

urlpatterns = [
    path('doctor-send-notification/', doctor_send_notification, name='doctor-send-notification'),
]

frontend/templates/base.html
<!DOCTYPE html> 
{% load static %}
<html lang="en">

<head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		<title>VACCINE || {% block title %}{% endblock title %}</title>

		<meta name="description" content="KHCITS - Child Immunization Tracking System">
		<meta name="keywords"
			content="KHCITS, Vaccine, Immunization, Vaccine Tracking System" />
		
		<!-- Favicons -->
		<link type="image/x-icon" href="{% static 'assets/img/favicon.png' %}" rel="icon">
		
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">
		
		<!-- Main CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
		

	
	</head>
	<body>

		<!-- Main Wrapper -->
		<div class="main-wrapper">
		
			<!-- Header -->
			<header class="header">
				<nav class="navbar navbar-expand-lg header-nav">
					<div class="navbar-header">
						<a id="mobile_btn" href="javascript:void(0);">
							<span class="bar-icon">
								<span></span>
								<span></span>
								<span></span>
							</span>
						</a>
						<a href="{% url 'core:index' %}" class="navbar-brand logo">
							
						</a>
					</div>
					<div class="main-menu-wrapper">
						<div class="menu-header">
							<a href="{% url 'core:index' %}" class="menu-logo">
								<img src="{% static 'assets/img/logo.png' %}" class="img-fluid" alt="Logo">
							</a>
							<a id="menu_close" class="menu-close" href="javascript:void(0);">
								<i class="fas fa-times"></i>
							</a>
						</div>

						<ul class="main-nav">
							<li class="">
								<a href="{% url 'core:index' %}" class="menu-logo">
									<img src="{% static 'assets/img/logo.png' %}" class="img-fluid" alt="Logo">
								</a>
							</li>
							<li class="">
								<a href="{% url 'core:index' %}">Home</a>
							</li>

							<li class="">
								<a href="{% url 'core:clients' %}">Hospitals</a>
							</li>
									
							<li class="has-submenu">
								<a href="#">Account <i class="fas fa-chevron-down"></i></a>
								{% if request.user.is_authenticated %}
							<ul class="submenu">
								<li><a href="{% url 'accounts:login' %}">Logout</a></li>
							</ul>
									
									{% else %}
									<ul class="submenu">
										<li><a href="{% url 'accounts:login' %}">Login</a></li>
										<li><a href="{% url 'accounts:register' %}">Register</a></li>
										<li><a href="#">Forgot Password</a></li>
									</ul>
								
								{% endif %}
							</li>
							{% if request.user.is_authenticated %}	

								{% if request.user.is_admin %}
									<li>
										<a href="{% url 'custom-admin:index' %}" target="_blank">Admin</a>
									</li>
								{% endif %}
							
							{% endif %}


							<li class="login-link">
								<a href="{% url 'accounts:login' %}">Login / Signup</a>
							</li>
						</ul>		 
					</div>		 
					<ul class="nav header-navbar-rht">
						<li class="nav-item contact-item">
							<div class="header-contact-img">
								<i class="far fa-hospital"></i>							
							</div>
							<div class="header-contact-detail">
								<p class="contact-header">Contact</p>
								<p class="contact-info-header"> +254 746 552127</p>
							</div>
						</li>
						{% if request.user.is_authenticated %}
						
						<li class="nav-item dropdown has-arrow logged-item">
							<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
								{% if request.user.is_doctor %}
									<span class="user-img">
										<img class="rounded-circle" src="{{ request.user.doctor.profile_picture_thumbnail.url }}" width="31" alt="Darren Elder">
									</span>
								{% elif request.user.is_parent %}
									<span class="user-img">
										<img src="{{ request.user.parent.profile_picture_thumbnail.url }}" alt="User Image" class="avatar-img rounded-circle">
									</span>
								{% endif %}
							</a>
							<div class="dropdown-menu dropdown-menu-right">
								<div class="user-header">
									<div class="avatar avatar-sm">
										{% if request.user.is_doctor %}
											<img src="{{ request.user.doctor.profile_picture_thumbnail.url }}" alt="User Image" class="avatar-img rounded-circle">
										{% elif request.user.is_parent %}
											<img src="{{ request.user.parent.profile_picture_thumbnail.url }}" alt="User Image" class="avatar-img rounded-circle">
										{% endif %}
									</div>
									<div class="user-text">
										<h6>{{ request.user.username }}</h6>
										{% if request.user.is_doctor %}
											<p class="text-muted mb-0">Doctor</p>
										{% else %}
											<p class="text-muted mb-0">Parent</p>
										{% endif %}
									</div>
								</div>
								{% if request.user.is_parent %}
									<a class="dropdown-item" href="{% url 'core:parent-dashboard' %}">Dashboard</a>
								{% elif request.user.is_doctor%}
									<a class="dropdown-item" href="{% url 'core:doctor-dashboard' %}">Dashboard</a>
								{% endif %}
								<a class="dropdown-item" href="#">Profile Settings</a>
								<a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
							</div>
						</li>
							
						{% else %}
							<li class="nav-item">
								<a class="nav-link header-login" href="{% url 'accounts:login' %}">login / Signup</a>
							</li>
							
						{% endif %}
					</ul>
				</nav>
			</header>
			<!-- /Header -->



            {% block body %}{% endblock body %}



			<!-- Footer -->
			<footer class="footer">
				
				<!-- Footer Top -->
				<div class="footer-top">
					<div class="container-fluid">
						<div class="row">
							<div class="col-lg-3 col-md-6">
							
								<!-- Footer Widget -->
								<div class="footer-widget footer-about">
									<div class="footer-logo">
										<img src="{% static 'assets/img/logo.png' %}" alt="logo" with="100px" height="100px">
									</div>
									<div class="footer-about-content">
										<p>Kenyatta Hosp track system is a child immunization registry and tracking system to register children,track their immunization records and send reminders to parents on their childs next visit. </p>
										<div class="social-icon">
											<ul>
												<li>
													<a href="#" target="_blank"><i class="fab fa-facebook-f"></i> </a>
												</li>
												<li>
													<a href="#" target="_blank"><i class="fab fa-twitter"></i> </a>
												</li>
												<li>
													<a href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
												</li>
												<li>
													<a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
												</li>
												<li>
													<a href="#" target="_blank"><i class="fab fa-dribbble"></i> </a>
												</li>
											</ul>
										</div>
									</div>
								</div>
								<!-- /Footer Widget -->
								
							</div>
							
							<div class="col-lg-3 col-md-6">
							
								<!-- Footer Widget -->
								<div class="footer-widget footer-menu">
									<h2 class="footer-title">For Parents</h2>
									<ul>
										<li><a href="#"><i class="fas fa-angle-double-right"></i>Hospitals</a></li>
										<li><a href="{% url 'accounts:login' %}"><i class="fas fa-angle-double-right"></i> Login</a></li>
										<li><a href="{% url 'accounts:register' %}"><i class="fas fa-angle-double-right"></i> Register</a></li>
										<li><a href="#"><i class="fas fa-angle-double-right"></i>Dashboard</a></li>
									</ul>
								</div>
								<!-- /Footer Widget -->
								
							</div>
							
							<div class="col-lg-3 col-md-6">
							
								<!-- Footer Widget -->
								<div class="footer-widget footer-menu">
									<h2 class="footer-title">For Doctors</h2>
									<ul>
										<li><a href="{% url 'accounts:login' %}"><i class="fas fa-angle-double-right"></i> Login</a></li>
										<li><a href="{% url 'accounts:register-doctor' %}"><i class="fas fa-angle-double-right"></i> Register</a></li>
										<li><a href="#"><i class="fas fa-angle-double-right"></i> Dashboard</a></li>
									</ul>
								</div>
								<!-- /Footer Widget -->
								
							</div>
							
							<div class="col-lg-3 col-md-6">
							
								<!-- Footer Widget -->
								<div class="footer-widget footer-contact">
									<h2 class="footer-title">Contact Us</h2>
									<div class="footer-contact-info">
										<div class="footer-address">
											<span><i class="fas fa-map-marker-alt"></i></span>
											<p>  X34H+8PC, Thika Superhighway Rd,<br> Nairobi, Kenya</p>
										</div>
										<p>
											<i class="fas fa-phone-alt"></i>
											+254 746 552 127
										</p>
										<p class="mb-0">
											<i class="fas fa-envelope"></i>
											contact@KHCITS.com
										</p>
									</div>
								</div>
								<!-- /Footer Widget -->
								
							</div>
							
						</div>
					</div>
				</div>
				<!-- /Footer Top -->
				
				<!-- Footer Bottom -->
                <div class="footer-bottom">
					<div class="container-fluid">
					
						<!-- Copyright -->
						<div class="copyright">
							<div class="row">
								<div class="col-md-6 col-lg-6">
									<div class="copyright-text">
										<p class="mb-0"><a href="#">KHCITS</a></p>
									</div>
								</div>
								<div class="col-md-6 col-lg-6">
								
									<!-- Copyright Menu -->
									<div class="copyright-menu">
										<ul class="policy-menu">
											<li><a href="{% url 'core:terms-and-conditions' %}">Terms and Conditions</a></li>
											<li><a href="{% url 'core:privacy-policy' %}">Policy</a></li>
										</ul>
									</div>
									<!-- /Copyright Menu -->
									
								</div>
							</div>
						</div>
						<!-- /Copyright -->
						
					</div>
				</div>
				<!-- /Footer Bottom -->
				
			</footer>
			<!-- /Footer -->
		   
	   </div>
	   <!-- /Main Wrapper -->
	  
		<!-- jQuery -->
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
		<script src="{% static 'assets/js/popper.min.js' %}"></script>
		<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
		
		<!-- Slick JS -->
		<script src="{% static 'assets/js/slick.js' %}"></script>
		
		<!-- Custom JS -->
		<script src="{% static 'assets/js/script.js' %}"></script>
		
	</body>
</html>

frontend/templates/doctor_appointments.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Appointments {% endblock title %}


{% block body %}


			
			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Appointments</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Appointments</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">

					<div class="row">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
							
							<!-- Profile Sidebar -->
							{% include 'partials/doctor_profile_sidebar.html' %}
							<!-- /Profile Sidebar -->
							
						</div>
						
						<div class="col-md-7 col-lg-8 col-xl-9">

							
							
							<div class="row">
								<div class="col-md-12">
									<h4 class="mb-4">Appoinments</h4>
									<div class="appointment-tab">
										
										<div class="tab-content">
										
											<!-- Upcoming Appointment Tab -->
											<div class="tab-pane show active" id="upcoming-appointments">
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">
															<table class="table table-hover table-center mb-0">
																<thead>
																	<tr>
																		<th>Patient Name</th>
																		<th>Appt Date</th>
																		<th>Parent Phone</th>
																		<th>Vaccine</th>
																		<th></th>
																	</tr>
																</thead>
																<tbody>
																	{% for child in appointments %}
																	
																	<tr>
																		<td>
																			<h2 class="table-avatar">
																				
																				<a href="{{ child.get_absolute_url }}">{{child.child.first_name}} {{child.child.last_name}} <span>{{ child.child.child_id }}</span></a>
																			</h2>
																		</td>
																		<td>{{ child.immunization_date | date:'d M Y' }} <span class="d-block text-info">{{ child.immunization_date | time }}</span></td>
																		<td>{{child.child.parent.phone_no}}</td>
																		<td>{{ child.vaccine.name }}</td>
																		<td class="text-right">
																			<div class="table-action">
																				<a href="javascript:void(0);" class="btn btn-sm bg-info-light">
																					<i class="far fa-eye"></i> View
																				</a>
																				
																				<a href="javascript:void(0);" class="btn btn-sm bg-success-light">
																					<i class="fas fa-check"></i> Accept
																				</a>
																				<a href="javascript:void(0);" class="btn btn-sm bg-danger-light">
																					<i class="fas fa-times"></i> Cancel
																				</a>
																			</div>
																		</td>
																	</tr>
																
																	
																	{% endfor %}
																	
																</tbody>
															</table>		
														</div>
													</div>
												</div>
											</div>
											<!-- /Upcoming Appointment Tab -->
											
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>

				</div>

			</div>		
			<!-- /Page Content -->
   

		

{% endblock body %}

frontend/templates/doctor_children_assigned.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Children {% endblock title %}


{% block body %}


			
			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Children</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Children</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">

					<div class="row">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
							
							<!-- Profile Sidebar -->
							{% include 'partials/doctor_profile_sidebar.html' %}
							<!-- /Profile Sidebar -->
							
						</div>
						
						<div class="col-md-7 col-lg-8 col-xl-9">

							
							
							<div class="row">
								<div class="col-md-12">
									<h4 class="mb-4">Children Records</h4>
									<div class="appointment-tab">
										<div class="text-right">		
											<a href="{% url 'core:create-child' %}" class="add-new-btn" >Add</a>
										</div>
										
										<div class="tab-content">
										
											<!-- Upcoming Appointment Tab -->
											<div class="tab-pane show active" id="upcoming-appointments">
												<div class="card card-table mb-0">
													<div class="card-body">
														<div class="table-responsive">
															<table class="table table-hover table-center mb-0">
																<thead>
																	<tr>
																		<th>Child's Name</th>
																		<th>Date Registerd</th>
																		<th>Parent</th>
																		<th>Phone</th>
																		<th class="text-center">Action</th>
																	</tr>
																</thead>
																<tbody>
																	{% for child in doctor_children %}

																	<tr>
																		<td>
																			<h2 class="table-avatar">
																				
																				<a href="{{ child.get_absolute_url }}">{{ child.first_name }} {{ child.last_name }}<span>#{{ child.child_id }}</span></a>
																			</h2>
																		</td>
																		<td>{{ child.created_at | date:'d M Y' }}<span class="d-block text-info">10.00 AM</span></td>
																		<td>{{ child.parent.user.username }}</td>
																		<td>{{ child.parent.user.phone_no }}</td>
																		<td class="text-center">
																			<div class="table-action">
																				<a href="{{ child.get_absolute_url }}" class="btn btn-sm bg-info-light">
																					<i class="far fa-eye"></i> View
																				</a>

																				<a href="{% url 'core:child-delete' child.uuid %}" class="btn btn-sm bg-danger-light">
																					<i class="fas fa-times"></i> Delete
																				</a>
																			</div>
																		</td>
																	</tr>
																	
																	{% endfor %}
																	
																</tbody>
															</table>		
														</div>
													</div>
												</div>
											</div>
											<!-- /Upcoming Appointment Tab -->
											
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>

				</div>

			</div>		
			<!-- /Page Content -->
   

		

{% endblock body %}

frontend/templates/doctor_send_notification.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Appointments {% endblock title %}


{% block body %}


			
			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Notifications</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Notifications</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">

					<div class="row">
						<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
							
							<!-- Profile Sidebar -->
							{% include 'partials/doctor_profile_sidebar.html' %}
							<!-- /Profile Sidebar -->
							
						</div>
						
						<div class="col-md-7 col-lg-8 col-xl-9">

							
							
							<div class="row">
								<div class="col-md-12">
									<h4 class="mb-4">Notifications</h4>
									<div class="appointment-tab">
										
										<div class="tab-content">
										
											<!-- Upcoming Appointment Tab -->
											<div class="chat-cont-right">
												<div class="chat-header">
													<a id="back_user_list" href="javascript:void(0)" class="back-user-list">
														<i class="material-icons">chevron_left</i>
													</a>
													<div class="media">
														<div class="media-img-wrap">
															<div class="avatar avatar-online">
																<img src="{% static 'assets/img/doctors/doctor-thumb-02.jpg' %}" alt="User Image" class="avatar-img rounded-circle">
															</div>
														</div>
														<div class="media-body">
															<div class="user-name">Dr. Darren Elder</div>
															<div class="user-status">online</div>
														</div>
													</div>
												</div>
												<div class="chat-body">
													<div class="chat-scroll">
														<ul class="list-unstyled">
															
															<li class="media received">
																<div class="avatar">
																	<img src="{% static 'assets/img/doctors/doctor-thumb-02.jpg' %}" alt="User Image" class="avatar-img rounded-circle">
																</div>
																<div class="media-body">
																	<div class="msg-box">
																		<div>
																			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,</p>
																			<ul class="chat-msg-info">
																				<li>
																					<div class="chat-time">
																						<span>10:17 AM</span>
																					</div>
																				</li>
																				<li><a href="#">Edit</a></li>
																			</ul>
																		</div>
																	</div>
																</div>
															</li>
															
														</ul>
													</div>
												</div>
												<div class="chat-footer">
													<form action="{% url 'notification:doctor-send-notification' %}" method="POST">{% csrf_token %}
														<div class="input-group">

															<textarea class="form-control" name="message" id="" cols="30" rows="10"></textarea>
															<button type="submit" class="btn msg-send-btn"><i class="fab fa-telegram-plane"></i></button>
														</div>
													</form>
												</div>
											</div>
											<!-- /Upcoming Appointment Tab -->
											
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>

				</div>

			</div>		
			<!-- /Page Content -->
   

		

{% endblock body %}

frontend/templates/hospitals.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Hospitals {% endblock title %}

{% block body %}

<div class="breadcrumb-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-12 col-12">
                <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Hospitals</li>
                    </ol>
                </nav>
                <h2 class="breadcrumb-title">Hospitals</h2>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="container-fluid">
        <div class="row row-grid">
    
            
            {% for client in clients %}
                <div class="col-md-6 col-lg-4 col-xl-3">
                    <div class="profile-widget">
                        <div class="doc-img">
                            <a href="doctor-profile.html">
                                <img class="img-fluid" alt="User Image" src="{% static 'assets/img/doctors/doctor-03.jpg' %}">
                            </a>
                            <a href="javascript:void(0)" class="fav-btn">
                                <i class="far fa-bookmark"></i>
                            </a>
                        </div>
                        <div class="pro-content">
                            <h3 class="title">
                                <a href="doctor-profile.html">{{ client.name }}</a> 
                                <i class="fas fa-check-circle verified"></i>
                            </h3>
                            <ul class="available-info">
                                <li>
                                    <i class="fas fa-map-marker-alt"></i>{{ client.county.name }}
                                </li>
                                <li>
                                    <i class="far fa-call"></i> {{ client.phone_no }}
                                </li>
                                <li>
                                    <i class="fas fa-map-marker-alt"></i>{{ client.address }} <i class="fas fa-info-circle" data-toggle="tooltip" title="Lorem Ipsum"></i>
                                </li>
                            </ul>
                           
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        
    </div>
</div>

{% endblock body %}

frontend/templates/parent_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    patient
{% endblock title %}

{% block body %}


			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Dashboard</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Dashboard</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">

					<div class="row">
						
						<!-- Profile Sidebar -->
						{% include 'partials/parent-profile-sidebar.html' %}
						<!-- / Profile Sidebar -->
						
						<div class="col-md-7 col-lg-8 col-xl-9">
							<div class="card">
								<div class="card-body pt-0">
								
									<!-- Tab Menu -->
									<nav class="user-tabs mb-4">
										<ul class="nav nav-tabs nav-tabs-bottom nav-justified">
											<li class="nav-item">
												<a class="nav-link active" href="#parent_children_tab" data-toggle="tab">Children</a>
											</li>
										</ul>
									</nav>
									<!-- /Tab Menu -->
									
									<!-- Tab Content -->
									<div class="tab-content pt-0">
										
										<!-- Appointment Tab -->
										<div id="parent_children_tab" class="tab-pane fade show active">
											<div class="card card-table mb-0">
												<div class="card-body">
													<div class="table-responsive">
														<table class="table table-hover table-center mb-0">
															<thead>
																<tr>
																	<th>Child</th>
																	<th>Date Added</th>
																	<th>Next Appointment</th>
																	<th>Completed</th>
																	<th></th>
																</tr>
															</thead>
															<tbody>
																{% for child in parent_children %}
																	
																	<tr>
																		<td>
																			<h2 class="table-avatar">
																				<a href="{{ child.get_absolute_url }}">{{ child.first_name }} {{ child.last_name }} <span>{{ child.child_id }}</span></a>
																			</h2>
																		</td>
																		<td>{{ child.created_at | date:'d M Y' }} <span class="d-block text-info">{{  child.created_at | time }}</span></td>
																		<td>12 Nov 2019</td>
																		<td><span class="badge badge-pill bg-success-light">Confirm</span></td>
																		<td class="text-right">
																			<div class="table-action">
																				<a href="javascript:void(0);" class="btn btn-sm bg-primary-light">
																					<i class="fas fa-print"></i> Print
																				</a>
																				<a href="{{ child.get_absolute_url }}" class="btn btn-sm bg-info-light">
																					<i class="far fa-eye"></i> View
																				</a>
																			</div>
																		</td>
																	</tr>
																
																{% endfor %}
																
															</tbody>
														</table>
													</div>
												</div>
											</div>
										</div>
										<!-- /Appointment Tab -->
										
										
									</div>
									<!-- Tab Content -->
									
								</div>
							</div>
						</div>
					</div>

				</div>

			</div>		
			<!-- /Page Content -->
   



{% endblock body %}
    